#pragma once
// =============================================================================
// Impact Style Profile — Per-body physics behavior authoring
// =============================================================================
//
// Defines how a body responds to impacts in a stylized (non-physically-accurate)
// way. Each body can be assigned an ImpactStyleProfile that modifies:
//
//   - Momentum transfer: scale how much force is exchanged on collision
//   - Vertical bias: exaggerate upward launches for dramatic hits
//   - Spin multiplier: amplify or reduce angular response
//   - Material curves: which restitution/friction curves to use
//   - Game feel hooks: hit-stop, time-scale, camera shake parameters
//
// Architecture:
//   Profiles are resolved per-contact-pair during the stylized solve pass.
//   When two bodies with different profiles collide, the "attacker" profile
//   (body with higher relative speed) takes precedence, or profiles are
//   blended based on relative mass.
//
// Design:
//   - Header-only, apc:: namespace
//   - No dynamic allocation
//   - Deterministic: profile resolution is order-independent
//   - C++17
//
// =============================================================================

#include "apc_math/apc_vec3.h"
#include "apc_math/apc_math_common.h"
#include "apc_style/apc_material_curve.h"
#include <cstdint>

namespace apc {

// =============================================================================
// Profile blend strategy — How to resolve two different profiles on collision
// =============================================================================
enum class ProfileBlendStrategy : uint8_t {
    ATTACKER_WINS,   // Faster body's profile is used
    HEAVIER_WINS,    // More massive body's profile is used
    AVERAGE,         // Average all parameters
    MAX,             // Take maximum of each parameter (most exaggerated)
    BODY_A_WINS,     // Always use body A's profile
    BODY_B_WINS      // Always use body B's profile
};

// =============================================================================
// ContactRegion — Body part classification for outcome tables
// =============================================================================
enum class ContactRegion : uint8_t {
    UNKNOWN   = 0,
    HEAD      = 1,
    TORSO     = 2,
    UPPER_ARM = 3,
    LOWER_ARM = 4,
    UPPER_LEG = 5,
    LOWER_LEG = 6,
    HAND      = 7,
    FOOT      = 8,
    SHOULDER  = 9,
    HIP       = 10
};

// =============================================================================
// ImpactStyleProfile — Complete per-body physics style definition
// =============================================================================
struct ImpactStyleProfile {
    // --- Profile Identification ---
    uint16_t profile_id = 0;
    const char* name = "default";  // Debug name (non-owning)

    // --- Momentum Transfer Modifiers ---
    // These scale the impulses generated by the solver AFTER physical resolution.
    float base_momentum_transfer = 1.0f;  // 0.0-2.0 (1.0 = realistic)
    float vertical_bias = 0.0f;            // 0.0-1.0 (exaggerate upward launches)
    float spin_multiplier = 1.0f;          // 0.0-3.0 (1.0 = realistic spin)

    // --- Material Curve References ---
    // IDs into a MaterialCurveRegistry. 0xFF = use solver defaults.
    uint8_t friction_curve_id = 0xFF;      // Angle-dependent friction curve
    uint8_t restitution_curve_id = 0xFF;   // Velocity-dependent restitution curve
    uint8_t momentum_curve_id = 0xFF;      // Speed-dependent momentum scale

    // --- Game Feel Hooks ---
    // These are read by the GameHookSystem to generate game-side effects.
    float hit_stop_duration_ms = 0.0f;     // Pause on impact (0 = disabled)
    float camera_shake_intensity = 0.0f;   // Camera shake (0 = disabled)
    float time_scale_on_impact = 1.0f;     // Slow-mo factor (1.0 = no change)
    float time_scale_duration_ms = 0.0f;   // Duration of time-scale effect

    // --- Impact Thresholds ---
    float light_impact_threshold = 2.0f;   // Below this: no game feel hooks
    float heavy_impact_threshold = 10.0f;  // Above this: maximum game feel
    float critical_impact_threshold = 25.0f; // Above this: cinematic effects

    // --- Default profile ---
    static ImpactStyleProfile make_default() {
        ImpactStyleProfile p;
        p.profile_id = 0;
        p.name = "default";
        p.base_momentum_transfer = 1.0f;
        p.vertical_bias = 0.0f;
        p.spin_multiplier = 1.0f;
        return p;
    }

    // --- "Light" profile: for small/fragile objects ---
    static ImpactStyleProfile make_light() {
        ImpactStyleProfile p;
        p.profile_id = 1;
        p.name = "light";
        p.base_momentum_transfer = 0.7f;
        p.vertical_bias = 0.3f;        // Gets knocked up easily
        p.spin_multiplier = 2.0f;      // Tumbles a lot
        p.hit_stop_duration_ms = 30.0f;
        p.camera_shake_intensity = 0.1f;
        p.light_impact_threshold = 1.0f;
        p.heavy_impact_threshold = 5.0f;
        p.critical_impact_threshold = 15.0f;
        return p;
    }

    // --- "Heavy" profile: for large/massive objects ---
    static ImpactStyleProfile make_heavy() {
        ImpactStyleProfile p;
        p.profile_id = 2;
        p.name = "heavy";
        p.base_momentum_transfer = 1.5f;  // Pushes others harder
        p.vertical_bias = 0.0f;           // Doesn't get launched
        p.spin_multiplier = 0.3f;         // Barely spins
        p.hit_stop_duration_ms = 80.0f;   // Big hit-stop on contact
        p.camera_shake_intensity = 0.5f;
        p.light_impact_threshold = 5.0f;
        p.heavy_impact_threshold = 15.0f;
        p.critical_impact_threshold = 40.0f;
        return p;
    }

    // --- "Ball" profile: for sports ball physics ---
    static ImpactStyleProfile make_ball() {
        ImpactStyleProfile p;
        p.profile_id = 3;
        p.name = "ball";
        p.base_momentum_transfer = 1.2f;
        p.vertical_bias = 0.15f;       // Slight upward kick
        p.spin_multiplier = 1.8f;      // Spin is important for balls
        p.hit_stop_duration_ms = 0.0f; // No hit-stop for continuous play
        p.camera_shake_intensity = 0.0f;
        p.time_scale_on_impact = 1.0f;
        p.light_impact_threshold = 3.0f;
        p.heavy_impact_threshold = 20.0f;
        p.critical_impact_threshold = 50.0f;
        return p;
    }

    // --- "Ragdoll" profile: for bodies transitioning to ragdoll ---
    static ImpactStyleProfile make_ragdoll() {
        ImpactStyleProfile p;
        p.profile_id = 4;
        p.name = "ragdoll";
        p.base_momentum_transfer = 1.3f;
        p.vertical_bias = 0.2f;
        p.spin_multiplier = 1.5f;
        p.hit_stop_duration_ms = 50.0f;
        p.camera_shake_intensity = 0.3f;
        p.light_impact_threshold = 1.5f;
        p.heavy_impact_threshold = 8.0f;
        p.critical_impact_threshold = 20.0f;
        return p;
    }
};

// =============================================================================
// ProfileRegistry — Collection of profiles for body assignment
// =============================================================================
struct ProfileRegistry {
    static constexpr uint32_t MAX_PROFILES = 32u;

    ImpactStyleProfile profiles[MAX_PROFILES];
    uint32_t count = 0;

    // -----------------------------------------------------------------
    // add — Register a profile. Returns its ID.
    // -----------------------------------------------------------------
    uint16_t add(const ImpactStyleProfile& profile) {
        if (count >= MAX_PROFILES) return 0xFFFF;
        profiles[count] = profile;
        profiles[count].profile_id = static_cast<uint16_t>(count);
        ++count;
        return profiles[count - 1].profile_id;
    }

    // -----------------------------------------------------------------
    // get — Retrieve a profile by ID. Returns default if invalid.
    // -----------------------------------------------------------------
    const ImpactStyleProfile* get(uint16_t id) const {
        if (id >= count) return nullptr;
        return &profiles[id];
    }

    // -----------------------------------------------------------------
    // resolve — Given two profile IDs, resolve to a single effective
    // profile using the specified blend strategy.
    // -----------------------------------------------------------------
    ImpactStyleProfile resolve(uint16_t id_a, uint16_t id_b,
                               ProfileBlendStrategy strategy,
                               float mass_a = 1.0f, float mass_b = 1.0f,
                               float speed_a = 0.0f, float speed_b = 0.0f) const
    {
        const ImpactStyleProfile* pa = get(id_a);
        const ImpactStyleProfile* pb = get(id_b);

        if (!pa && !pb) return ImpactStyleProfile::make_default();
        if (!pa) return *pb;
        if (!pb) return *pa;

        switch (strategy) {
        case ProfileBlendStrategy::BODY_A_WINS:
            return *pa;

        case ProfileBlendStrategy::BODY_B_WINS:
            return *pb;

        case ProfileBlendStrategy::ATTACKER_WINS:
            return (speed_a >= speed_b) ? *pa : *pb;

        case ProfileBlendStrategy::HEAVIER_WINS:
            return (mass_a >= mass_b) ? *pa : *pb;

        case ProfileBlendStrategy::MAX: {
            ImpactStyleProfile result = *pa;
            result.base_momentum_transfer = std::max(pa->base_momentum_transfer,
                                                      pb->base_momentum_transfer);
            result.vertical_bias = std::max(pa->vertical_bias, pb->vertical_bias);
            result.spin_multiplier = std::max(pa->spin_multiplier, pb->spin_multiplier);
            result.hit_stop_duration_ms = std::max(pa->hit_stop_duration_ms,
                                                     pb->hit_stop_duration_ms);
            result.camera_shake_intensity = std::max(pa->camera_shake_intensity,
                                                       pb->camera_shake_intensity);
            return result;
        }

        case ProfileBlendStrategy::AVERAGE:
        default: {
            ImpactStyleProfile result = *pa;
            result.base_momentum_transfer = (pa->base_momentum_transfer +
                                              pb->base_momentum_transfer) * 0.5f;
            result.vertical_bias = (pa->vertical_bias + pb->vertical_bias) * 0.5f;
            result.spin_multiplier = (pa->spin_multiplier + pb->spin_multiplier) * 0.5f;
            result.hit_stop_duration_ms = (pa->hit_stop_duration_ms +
                                            pb->hit_stop_duration_ms) * 0.5f;
            result.camera_shake_intensity = (pa->camera_shake_intensity +
                                              pb->camera_shake_intensity) * 0.5f;
            result.time_scale_on_impact = (pa->time_scale_on_impact +
                                            pb->time_scale_on_impact) * 0.5f;
            return result;
        }
        }
    }

    // -----------------------------------------------------------------
    // setup_defaults — Populate with standard profiles.
    // -----------------------------------------------------------------
    uint32_t setup_defaults() {
        count = 0;
        add(ImpactStyleProfile::make_default());
        add(ImpactStyleProfile::make_light());
        add(ImpactStyleProfile::make_heavy());
        add(ImpactStyleProfile::make_ball());
        add(ImpactStyleProfile::make_ragdoll());
        return count;
    }
};

// =============================================================================
// BodyStyleAssignment — Maps body indices to profile IDs
// =============================================================================
struct BodyStyleAssignment {
    static constexpr uint32_t MAX_BODIES = 256u;

    uint16_t profile_ids[MAX_BODIES];
    ContactRegion regions[MAX_BODIES]; // Optional contact region per body

    void reset() {
        for (uint32_t i = 0; i < MAX_BODIES; ++i) {
            profile_ids[i] = 0;
            regions[i] = ContactRegion::UNKNOWN;
        }
    }

    void assign(uint32_t body_index, uint16_t profile_id,
                ContactRegion region = ContactRegion::UNKNOWN) {
        if (body_index >= MAX_BODIES) return;
        profile_ids[body_index] = profile_id;
        regions[body_index] = region;
    }

    uint16_t get_profile(uint32_t body_index) const {
        if (body_index >= MAX_BODIES) return 0;
        return profile_ids[body_index];
    }

    ContactRegion get_region(uint32_t body_index) const {
        if (body_index >= MAX_BODIES) return ContactRegion::UNKNOWN;
        return regions[body_index];
    }
};

} // namespace apc
